{{- with .Values.authentication.forwardAuth }}

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "longhorn.name" $ }}-forward-auth
  labels:
    {{- include "longhorn.labels" $ | nindent 4 }}
spec:
  forwardAuth:
    address: {{ .address | quote }}

{{- end }}
