apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-users
  labels:
    {{- include "authelia.labels" . | nindent 4 }}
data:
  users.yaml: |
    {{- if gt (len .Values.users) 0}}
    users:
    {{- range .Values.users }}
      {{ .username }}:
        displayname: {{ .displayname }}
        email: {{ .email }}
        password: {{ .password }}
    {{- end }}
    {{- else }}
    users: [ ]
    {{- end }}
