apiVersion: v1
kind: Secret
metadata:
  name: authelia-secrets
  labels:
    {{- include "authelia.labels" . | nindent 4 }}
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (print .Release.Name "-secret")) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}

  # JWT Secret
  {{- $jwtSecret := (get $secretData "JWT_TOKEN") | default (randAlphaNum 64 | b64enc) }}
  JWT_TOKEN: {{ $jwtSecret | quote }}

  # Session Secret
  {{- $sessionSecret := (get $secretData "SESSION_ENCRYPTION_KEY") | default (randAlphaNum 64 | b64enc) }}
  SESSION_ENCRYPTION_KEY: {{ $sessionSecret | quote }}

  # Storage Secret
  {{- $storageSecret := (get $secretData "STORAGE_ENCRYPTION_KEY") | default (randAlphaNum 64 | b64enc) }}
  STORAGE_ENCRYPTION_KEY: {{ $storageSecret | quote }}

  {{- if .Values.authelia.configMap.identity_providers.oidc.enabled }}

  # OIDC Hmac Secret
  {{- $oidcHmacSecret := (get $secretData "OIDC_HMAC_SECRET") | default (randAlphaNum 64 | b64enc) }}
  OIDC_HMAC_SECRET: {{ $oidcHmacSecret | quote }}

  # OIDC Private Key
  {{- $oidcPrivateKey := (get $secretData "OIDC_PRIVATE_KEY") | default (genPrivateKey "rsa" | b64enc) }}
  OIDC_PRIVATE_KEY: {{ $oidcPrivateKey | quote }}

  {{- end }}
