apiVersion: v1
kind: Secret
metadata:
  name: authelia-secrets
  labels:
    {{- include "authelia.labels" . | nindent 4 }}
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (print .Release.Name "-secret")) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}

  # JWT Secret
  {{- $jwtSecret := (get $secretData "JWT_TOKEN") | default (randAlphaNum 64) }}
  JWT_TOKEN: {{ $jwtSecret | quote }}

  # Session Secret
  {{- $sessionSecret := (get $secretData "SESSION_ENCRYPTION_KEY") | default (randAlphaNum 64) }}
  SESSION_ENCRYPTION_KEY: {{ $sessionSecret | quote }}

  # Storage Secret
  {{- $storageSecret := (get $secretData "STORAGE_ENCRYPTION_KEY") | default (randAlphaNum 64) }}
  STORAGE_ENCRYPTION_KEY: {{ $storageSecret | quote }}
