apiVersion: v1
kind: Secret
metadata:
  name: {{ print .Release.Name "-secret" }}
  labels:
    {{- include "authelia.labels" . | nindent 4 }}
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (print .Release.Name "-secret")) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}

  # JWT Secret
  {{- $jwtSecret := (get $secretData "jwt-secret") | default (randAlphaNum 64) }}
  jwt-secret: {{ $jwtSecret | quote }}

  # Session Secret
  {{- $sessionSecret := (get $secretData "session-secret") | default (randAlphaNum 64) }}
  session-secret: {{ $sessionSecret | quote }}

  # Storage Secret
  {{- $storageSecret := (get $secretData "storage-secret") | default (randAlphaNum 64) }}
  storage-secret: {{ $storageSecret | quote }}
