apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "authelia.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9091
    {{- if .Values.metrics.enable }}
    - name: metrics
      protocol: TCP
      port: {{ .Values.metrics.port }}
      targetPort: 9959
    {{- end }}
