apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homer.name" $ }}-config
  labels:
    {{- include "homer.labels" $ | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
