{{- with .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "homer.name" $ }}
  labels:
    {{- include "homer.labels" $ | nindent 4 }}
spec:
  type: {{ .type }}
  selector:
    app: homer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      {{- if and (eq .type "LoadBalancer") .loadBalancerIP }}
      loadBalancerIP: {{ .loadBalancerIP }}
      {{- end }}
{{- end }}
