apiVersion: v1
kind: Service
metadata:
  name: {{ include "torrent.name" $ }}-qbittorrent
  labels:
    {{- include "torrent.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "torrent.name" $ }}-qbittorrent
  ports:
    - name: webui
      protocol: TCP
      port: 80
      targetPort: 8080
