apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pihole.name" . }}-config
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
data:
  adlists.list: |
    {{- range .Values.adlists }}
    {{ . }}
    {{- end }}
  whitelist.txt: |
    {{- range .Values.blocking.allowlist }}
    {{ . }}
    {{- end }}
  blacklist.txt: |
    {{- range .Values.blocking.denylist }}
    {{ . }}
    {{- end }}
  regex.list: |
    {{- range .Values.blocking.regex }}
    {{ . }}
    {{- end }}
  dnsmasq.conf: |
    addn-hosts=/etc/addn-hosts
    {{-  range $host, $cnames := .Values.localDnsEntries.CNAME }}
    cname={{- range $cnames -}}{{- . -}},{{- end -}}{{- $host }}
    {{- end }}
  addn-hosts: |
    {{- range $host, $ip := .Values.localDnsEntries.A }}
    {{ $ip -}}{{- "\t" -}}{{- $host }}
    {{- end }}
