{{ with .Values.authentication.password -}}
{{- if .enabled -}}

{{- $secret := lookup "v1" "Secret" $.Release.Namespace .secretName | default dict -}}
{{- $data := get $secret "data" | default dict -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl .secretName $ | quote }}
  labels:
    {{- include "pihole.labels" $ | nindent 4 }}
data:
  {{ .passwordKey }}: {{ get $data .passwordKey | default (randAlphaNum 24 | quote) }}

{{- end -}}
{{- end -}}
