{{ with .Values.services.piholeWeb -}}
{{- if .enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole.name" $ }}-web
  labels:
    {{- include "pihole.labels" $ | nindent 4 }}
spec:
  type: {{ .type }}
  selector:
    app: pihole
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
  {{- if and (eq .type "LoadBalancer") .loadBalancerIP }}
  loadBalancerIP: {{ .loadBalancerIP }}
  {{- end }}
{{- end }}
{{- end }}
