apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
  labels:
    app: unbound
    {{- include "pihole.labels" $ | nindent 4 }}
spec:
  {{- with .Values.scaling }}
  replicas: {{ .replicas }}
  strategy:
    type: {{ .strategy }}
    {{- if eq .strategy "RollingUpdate"}}
    rollingUpdate:
      maxSurge: {{ .maxSurge }}
      maxUnavailable: {{ .maxUnavailable }}
    {{- end }}
  {{- end }}
  selector:
    matchLabels:
      app: unbound
  template:
    metadata:
      labels: 
        app: unbound
        {{- include "pihole.labels" $ | nindent 8 }}
    spec:
      restartPolicy: Always
      containers:
        - name: unbound
          image: {{ .Values.images.unbound }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
          livenessProbe:
            tcpSocket:
              port: dns-tcp
            initialDelaySeconds: 15
            periodSeconds: 30
      {{- if .Values.scaling.spreadAcrossNodes }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: node
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: unbound
      {{- end }}
