apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
  labels:
    app: unbound
    {{- include "pihole.labels" $ | nindent 4 }}
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: unbound
  template:
    metadata:
      labels: 
        app: unbound
        {{- include "pihole.labels" $ | nindent 8 }}
    spec:
      restartPolicy: Always
      containers:
        - name: unbound
          image: {{ .Values.images.unbound }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
          livenessProbe:
            tcpSocket:
              port: dns-tcp
            initialDelaySeconds: 15
            periodSeconds: 30
